### ISSUE TITLE
pimpyaml for the slim framework

### ISSUE THREAD

**Issue by Stephan123** [donkyfronky/pimpyaml-container#1]
Hello,

is there a way to combine pimpyaml with the slim framework ?

Your sincerly

Stephan Krauss

**Comment by donkyfronky** [comment]
Yeah,

_SimpleContainer_ implements _ContainerInterface_ so you can simply write:

  $conf_file = __DIR__.'/config.yml';
  $config = \SwissArmy\ConfigHandler::loadConf($conf_file);
  $container = new \SwissArmy\SimpleContainer($config);
  $app = new \Slim\App($container);


intended for Slim 3.x.y
